remote_theme: ISSAE/architect

name: Programmation Avancée TP2

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: TP 2
description: Programmation Avancée et Patron de conception en Java

google_analytics: UA-29708002-2

repository: ISSAE/nfp121.tp2

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

